### ISSUE TITLE
Support nested keypaths for filters and computed properties

### ISSUE THREAD

**Issue by aristidesfl** [yyx990803/vue#340]
Vue.$data supports nested objects which can be navigated using the `.` operator just like normal javascript objects.

When defining filters and computed properties however, one is currently limited to a flat structure. For improved organisation and readability, sometimes it would be useful to be able to describe filters and computed properties also in a hierarchical way.

```
new Vue
  data: 
    email: "example@mail.com"
    name: ""
    ...
  filters:
    currency: (value) -> ...
    validators:
      email: (value) -> ...
      name: (value) -> ...
      phone: (value) -> ...
```
