### ISSUE TITLE
Transition stuck on leave

### ISSUE THREAD

**Issue by knownasilya** [yyx990803/vue#694]
Having some trouble with the Transitions API. I upgraded to 0.11.4 recently, and can't get this to work.

```html
<div class="directions-content" v-show="showDirectionsForm" v-transition="expand">
  <!-- more markup -->
</div>
```

```less
.directions-content {
    transition: height .3s ease, opacity .3s ease;
    height: 100px;
    margin-top: 6px;
    border-top: 1px solid #eee;
    padding: 0.2em;

    &.expand-enter,
    &.expand-leave {
      height: 0;
      opacity: 0;
    }
}
```

```js
methods: {
    toggleDirectionsForm: function () {
      var show = this.$get('showDirectionsForm');

      if (show) {
        this.$set('showDirectionsForm', false);
      }
      else {
        this.$set('showDirectionsForm', true);
      }
    }
}
```

The result of toggling `showDirectionsForm` is the same as the initial state:

```html
<div class="directions-content expand-leave" style="display: none;">
  <!-- more markup -->
</div>
```
